## _Medical Insurance Costs_

Pada kasus ini, terdapat data tentang informasi kesehatan dan biaya yang harus dikeluarkan oleh asuransi kesehatan. Infomasi terkait dengan data _medical insurance cost_ adalah sebagai berikut,

1. Age: Usia penerima manfaat
2. Sex: Gender penerima manfaat (_male_, _femele_)
3. Bmi : Body Mass Index
4. Children: Jumlah anak/tanggungan yang dicover oleh pihak asuransi
5. Smoker: Status perokok (_yes_, _no_)
6. Region: Wilayah tempat tinggal penerima manfaat
7. Charges: Biaya yang dikeluarkan oleh asuransi

### Tantangan

Buatlah model regresi untuk memprediksi biaya yang harus dikeluarkan oleh pihak asuransi berdasarkan data. Validasi performa model regresi Anda dengan nilai ***R-squared ($R^2$)***

#### _Tasks_

1. Pastikan semua variabel kategorial diolah dengan baik. (Gunakan fitur mapping pada pandas)
2. Cek kondisi multicollinearity untuk semua variabel independen. Jika ada, antar variabel apakah itu?
3. Pastikan model menggunakan variabel yang tidak memiliki nilai multicollinearity yang tinggi
4. (Hints) Anda dapat menggunakan nilai ***Variance Inflation Factor (VIF)*** untuk mengetahui tingkat multicollinearity pada sebuah variabel independent.
5. Evaluasi model yang Anda buat dengan nilai $R^2$
6. Simpulkan, variabel independen apa saja yang dapat digunakan untuk menghasilkan model regresi yang baik pada kasus _medical insurance costs_?

#### (Hints) Interpretasi Nilai VIF

- 1 - variabel indenpenden tidak memiliki korelasi dengan variabel independen yang lain
- 1 < VIF < 5 - variabel independen sedikit memiliki korelasi dengan variabel independen yang lain
- VIF > 5 - variabel independen memiliki korelasi yang kuat dengan variabel independen lainnya
- VIF > 10 - variabel independen miliki korelasi yang sangat kuat dengan variabel independen dan perlu diperhatikan lebih lanjut

#### (Hints) Implementasi Perhitungan VIF

VIF dapat dihitung secara langsung dengan menggunakan library dari `statsmodels`

#### (Hints) Scatterplot Korelasi Antar Variabel

![var_cor](assets/var_corr.png)

In [69]:
# Buka file .csv

import pandas as pd
import numpy as np

df = pd.read_csv('data/insurance.csv')

display(df.head())

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [70]:
# Mapping

new_sex = {
    'female': 0,
    'male': 1
}
new_smoker = {
    'no': 0,
    'yes': 1
}
new_region = {
    'northwest' : 0,
    'southwest' : 1,
    'southeast' : 2,
    'northeast' : 3 
    
}

df['sex'] = df['sex'].map(new_sex)
df['smoker'] = df['smoker'].map(new_smoker)
df['region'] = df['region'].map(new_region)


df.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       1  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       0  21984.47061
4   32    1  28.880         0       0       0   3866.85520

In [71]:
# cek multicollinearity

from statsmodels.stats.outliers_influence import variance_inflation_factor

def calc_VIF(x):
  vif= pd.DataFrame()
  vif['variables']=x.columns
  vif["VIF"]=[variance_inflation_factor(x.values,i) for i in range(x.shape[1])]

  return(vif)

In [72]:
X = df.iloc[:,:-1]
calc_VIF(X)

  variables       VIF
0       age  7.588734
1       sex  2.002652
2       bmi  9.938670
3  children  1.799980
4    smoker  1.261195
5    region  2.789478

In [73]:
df.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       1  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       0  21984.47061
4   32    1  28.880         0       0       0   3866.85520

In [74]:
# Slice data

X = df.iloc[:, 0:6].values
y = df.iloc[:, -1].values

# Reshape ym
y = y.reshape(len(y), 1)
y.shape

(1338, 1)

In [75]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=30)

mlr = LinearRegression()

# Fit feature
mlr.fit(X_train, y_train)

# Predict
y_pred = mlr.predict(X_test)

# Compare value vs prediction

com = np.concatenate((y_test, y_pred), axis = 1)
com

array([[ 4.19190970e+04,  3.54415576e+04],
       [ 3.65934600e+03,  5.82868917e+03],
       [ 4.74634400e+03,  5.82370136e+03],
       [ 3.27341863e+04,  2.63842587e+04],
       [ 9.14456500e+03,  1.29304913e+04],
       [ 4.73826820e+03,  6.71103351e+03],
       [ 1.28900577e+04,  4.97504011e+03],
       [ 3.02846429e+04,  9.53070009e+03],
       [ 3.97255180e+04,  3.33984358e+04],
       [ 1.21249924e+04,  1.11157766e+04],
       [ 6.28223500e+03,  7.95544815e+03],
       [ 8.11668000e+03,  1.01351115e+04],
       [ 4.16760811e+04,  3.52479603e+04],
       [ 1.02314999e+04,  1.12609946e+04],
       [ 1.71222700e+03,  1.65937389e+03],
       [ 2.70379141e+04,  3.60710362e+04],
       [ 8.12440840e+03,  1.20487950e+04],
       [ 9.30189355e+03,  9.00487959e+03],
       [ 1.86082620e+04,  2.91400078e+04],
       [ 8.28368070e+03,  1.13909215e+04],
       [ 1.63573365e+03,  1.17596001e+03],
       [ 5.72900530e+03,  8.45654196e+03],
       [ 9.26479700e+03,  8.04389683e+03],
       [ 7.73185785e+03,  1.10021882e+04],
       [ 2.35682720e+04,  3.32054619e+04],
       [ 4.72910550e+04,  3.93270703e+04],
       [ 1.24952908e+04,  1.46764351e+04],
       [ 4.50033925e+03,  3.71102994e+03],
       [ 7.26570250e+03,  1.07690300e+04],
       [ 1.13969002e+04,  1.50611793e+04],
       [ 3.59417085e+03,  1.94140001e+03],
       [ 4.45854559e+04,  3.08934252e+04],
       [ 2.39609590e+03,  1.75098914e+03],
       [ 1.05797110e+04,  1.51035412e+04],
       [ 1.21469710e+04,  1.26358178e+04],
       [ 5.93437980e+03,  9.10218847e+03],
       [ 2.15436100e+03,  2.32650235e+03],
       [ 6.38937785e+03,  6.73300665e+03],
       [ 1.63256445e+03,  4.65460107e+02],
       [ 5.64971500e+03,  8.64171837e+03],
       [ 6.79945800e+03,  7.24912265e+03],
       [ 2.48733849e+04,  3.44679670e+04],
       [ 2.72132080e+03,  2.81786010e+03],
       [ 1.19445943e+04,  1.43227734e+04],
       [ 6.78135420e+03,  1.08026529e+04],
       [ 3.97227462e+04,  3.04800177e+04],
       [ 5.03126955e+03,  5.71142045e+03],
       [ 1.13701100e+03,  3.22340045e+03],
       [ 1.26098870e+04,  2.60905921e+03],
       [ 3.92575820e+03,  5.86707229e+03],
       [ 8.52200300e+03,  1.14795716e+04],
       [ 8.97818510e+03,  1.30749274e+04],
       [ 1.22338280e+04,  1.23300780e+04],
       [ 2.04568525e+03,  1.14803750e+03],
       [ 7.37177200e+03,  1.13632021e+04],
       [ 8.89113950e+03,  7.80029565e+03],
       [ 2.24620438e+04,  3.17644754e+04],
       [ 2.19844706e+04,  3.31530744e+03],
       [ 1.27309996e+04,  1.32285405e+04],
       [ 4.56419145e+03,  5.30683541e+03],
       [ 1.06023850e+04,  1.51203253e+04],
       [ 5.70916440e+03,  1.12839510e+04],
       [ 1.10855868e+04,  1.12105058e+04],
       [ 4.32041085e+03,  7.66767991e+03],
       [ 1.62728245e+03, -7.18706400e+02],
       [ 1.89631719e+04,  8.32510723e+03],
       [ 1.01061342e+04,  1.05805330e+04],
       [ 3.20878700e+03,  1.58802789e+03],
       [ 5.11650040e+03,  2.76324609e+03],
       [ 1.13659520e+04,  1.49375889e+04],
       [ 1.29571180e+04,  1.08326431e+04],
       [ 2.45721115e+03,  2.67971251e+03],
       [ 1.96478000e+03,  2.29455024e+02],
       [ 9.71584100e+03,  1.00552730e+04],
       [ 1.51615344e+04,  1.63724619e+04],
       [ 3.16745585e+03, -3.59659055e+02],
       [ 8.34716430e+03,  1.28151594e+04],
       [ 9.44725035e+03,  1.01057453e+04],
       [ 2.12593779e+04,  3.13313912e+04],
       [ 2.63299200e+03,  4.12468924e+03],
       [ 2.19818985e+03,  1.37600825e+03],
       [ 8.24058960e+03,  1.13149589e+04],
       [ 7.05002130e+03,  9.82664785e+03],
       [ 2.10821600e+04,  3.08959666e+04],
       [ 1.61576670e+03,  1.32427078e+03],
       [ 1.34708600e+04,  1.67770584e+04],
       [ 2.35630162e+04,  9.67786861e+03],
       [ 1.49015167e+04,  1.77136873e+04],
       [ 8.78246900e+03,  9.14215600e+03],
       [ 8.59682780e+03,  1.14152205e+04],
       [ 1.33905590e+04,  1.40288951e+04],
       [ 1.13940655e+04,  1.40639509e+04],
       [ 3.43031672e+04,  2.69471090e+04],
       [ 1.88061455e+04,  1.11229242e+04],
       [ 2.91413603e+04,  3.68025867e+04],
       [ 1.96733357e+04,  5.44400440e+03],
       [ 9.61766245e+03,  1.03014195e+04],
       [ 2.30400220e+03,  1.60285798e+03],
       [ 6.55507035e+03,  7.43576510e+03],
       [ 4.23036922e+04,  3.58495220e+04],
       [ 4.09741649e+04,  3.49526903e+04],
       [ 1.15348726e+04,  8.90465109e+03],
       [ 9.22240260e+03,  1.02743528e+04],
       [ 3.23843570e+03,  8.41600238e+03],
       [ 3.98365190e+04,  3.32088035e+04],
       [ 1.61387620e+04,  2.64800323e+04],
       [ 6.41417800e+03,  7.25571495e+03],
       [ 4.28568380e+04,  3.60952740e+04],
       [ 2.49152209e+04,  3.36719117e+04],
       [ 1.97295000e+03,  2.05785868e+03],
       [ 2.55171136e+04,  1.07477242e+04],
       [ 7.98581500e+03,  7.15887730e+03],
       [ 3.86120965e+03,  1.15607052e+03],
       [ 1.82592160e+04,  2.81251655e+04],
       [ 3.17201800e+03,  5.89171386e+03],
       [ 5.35407465e+03,  4.50215024e+03],
       [ 1.13532276e+04,  1.24764469e+04],
       [ 2.49150463e+04,  1.04334005e+04],
       [ 8.41346305e+03,  9.79433480e+03],
       [ 8.56986180e+03,  1.52840353e+04],
       [ 2.77242887e+04,  4.55821494e+03],
       [ 7.65077375e+03,  1.28851732e+04],
       [ 2.78087251e+04,  3.65653953e+04],
       [ 1.36073687e+04,  1.46204801e+04],
       [ 2.02348547e+04,  2.95349925e+04],
       [ 1.34150381e+04,  1.06855112e+04],
       [ 1.34579608e+04,  1.40662601e+04],
       [ 7.72685400e+03,  8.74392524e+03],
       [ 2.10985540e+04,  3.10563276e+04],
       [ 1.07044700e+04,  1.21969543e+04],
       [ 1.11507800e+04,  1.13263016e+04],
       [ 3.85775925e+03,  5.87045216e+03],
       [ 4.45013982e+04,  3.41042619e+04],
       [ 3.48286540e+04,  2.71889616e+04],
       [ 1.22243509e+04,  1.21048294e+04],
       [ 1.52631200e+03,  2.90846529e+03],
       [ 4.95776624e+04,  4.08743859e+04],
       [ 1.68849240e+04,  2.54051323e+04],
       [ 1.30473324e+04,  1.22301579e+04],
       [ 4.34946200e+03,  6.79563550e+03],
       [ 1.09239332e+04,  1.29714157e+04],
       [ 1.04939458e+04,  1.01946677e+04],
       [ 4.03224070e+03,  3.38213075e+03],
       [ 5.25908294e+04,  3.74814724e+04],
       [ 6.31195200e+03,  7.92687704e+03],
       [ 1.12443769e+04,  1.12005227e+04],
       [ 3.57799900e+03,  6.48474263e+03],
       [ 5.69343050e+03,  3.32458752e+03],
       [ 7.73142710e+03,  9.95022506e+03],
       [ 2.30654207e+04,  3.30403241e+04],
       [ 1.10936229e+04,  1.62006289e+04],
       [ 8.62754110e+03,  6.92486331e+03],
       [ 6.47401300e+03,  1.10319885e+04],
       [ 7.22278625e+03,  6.10482535e+03],
       [ 6.77596100e+03,  9.41249566e+03],
       [ 7.24381360e+03,  8.54510330e+03],
       [ 1.63304440e+03,  5.19774175e+03],
       [ 1.18407751e+04,  1.25483313e+04],
       [ 1.15384210e+04,  1.78257549e+04],
       [ 2.21760120e+03,  5.72782016e+03],
       [ 9.62033070e+03,  1.05448566e+04],
       [ 3.77425757e+04,  3.17625261e+04],
       [ 9.87568040e+03,  1.46571713e+04],
       [ 8.93093455e+03,  1.00060644e+04],
       [ 9.80088820e+03,  1.54191022e+04],
       [ 3.69106080e+04,  1.54524340e+04],
       [ 4.19492441e+04,  3.48018130e+04],
       [ 5.97683110e+03,  8.32201215e+03],
       [ 4.46272180e+03,  6.93575137e+03],
       [ 2.48373600e+03,  2.19853218e+03],
       [ 6.60036100e+03,  8.45499009e+03],
       [ 1.16581151e+04,  1.22324327e+04],
       [ 6.68643130e+03,  5.83556857e+03],
       [ 4.04055825e+03,  5.16812779e+03],
       [ 4.00033322e+04,  3.31977005e+04],
       [ 9.19383850e+03,  7.17280086e+03],
       [ 1.39152870e+03,  3.51744696e+03],
       [ 3.99417780e+03,  1.05125252e+04],
       [ 1.38447972e+04,  1.45642171e+04],
       [ 1.95155416e+04,  3.03137273e+04],
       [ 1.04070858e+04,  1.10085235e+04],
       [ 1.07136440e+04,  1.42536645e+04],
       [ 2.15046900e+03,  1.45395861e+03],
       [ 2.58585065e+03,  8.74419142e+02],
       [ 4.70555321e+04,  3.91771435e+04],
       [ 3.63077983e+04,  2.81220309e+04],
       [ 1.67763040e+04,  2.76088978e+04],
       [ 6.11323105e+03,  7.42083035e+03],
       [ 5.51354021e+04,  3.13397253e+04],
       [ 9.50431030e+03,  1.48649908e+04],
       [ 1.70470015e+03, -2.80633819e+01],
       [ 2.92706470e+03,  9.65661046e+03],
       [ 1.34290354e+04,  1.38235525e+04],
       [ 1.12534210e+04,  1.19446096e+04],
       [ 7.32373482e+03,  2.26413313e+03],
       [ 1.18424420e+04,  1.25305142e+04],
       [ 1.64557078e+04,  1.55701655e+04],
       [ 3.78297242e+04,  3.13843923e+04],
       [ 3.69502567e+04,  3.05033230e+04],
       [ 5.26636560e+03,  5.49076896e+03],
       [ 7.26174100e+03,  9.88090508e+03],
       [ 2.30829553e+04,  2.99771479e+03],
       [ 6.49688600e+03,  7.64970837e+03],
       [ 4.64675900e+03,  7.08694671e+03],
       [ 3.61494835e+04,  2.81082190e+04],
       [ 3.18051010e+03,  1.46452047e+03],
       [ 2.47333410e+03,  5.18864015e+03],
       [ 4.38138661e+04,  3.71273121e+04],
       [ 4.27605022e+04,  3.52897229e+04],
       [ 4.61135110e+04,  3.71975749e+04],
       [ 4.92291590e+03,  6.42316741e+03],
       [ 6.18429940e+03,  7.65590936e+03],
       [ 4.74964944e+04,  3.89087179e+04],
       [ 8.42806930e+03,  6.50009721e+03],
       [ 4.41515880e+03,  5.90474557e+03],
       [ 4.66614424e+04,  3.83654087e+04],
       [ 3.17161490e+03,  5.98240418e+03],
       [ 2.45972010e+03,  3.24219160e+03],
       [ 1.15761300e+04,  1.68705956e+04],
       [ 1.71795220e+04,  2.86952320e+04],
       [ 7.41852200e+03,  1.03180927e+04],
       [ 4.61305265e+04,  3.81198232e+04],
       [ 7.44840395e+03,  1.23912157e+04],
       [ 2.10411340e+03,  2.10511798e+03],
       [ 4.13408245e+03,  2.88279989e+03],
       [ 8.31083915e+03,  9.71707719e+03],
       [ 6.60020595e+03,  9.70373074e+03],
       [ 1.24048791e+04,  7.76623967e+03],
       [ 6.94090985e+03,  7.26700268e+03],
       [ 2.20769745e+03,  3.50750796e+03],
       [ 1.58288217e+04,  9.51305636e+03],
       [ 1.10825772e+04,  1.09189812e+04],
       [ 8.54769130e+03,  1.03136522e+04],
       [ 1.18426238e+04,  1.29627895e+04],
       [ 2.56565753e+04,  1.02455905e+04],
       [ 2.21440320e+04,  3.18029644e+04],
       [ 3.81262465e+04,  3.03410321e+04],
       [ 1.10731760e+04,  1.14355972e+04],
       [ 6.54819505e+03,  7.22302431e+03],
       [ 3.55855760e+04,  2.82080916e+04],
       [ 1.42105359e+04,  1.63289120e+04],
       [ 1.50197601e+04,  1.47308312e+04],
       [ 1.01977722e+04,  9.47700341e+03],
       [ 2.02697410e+03,  6.10157131e+03],
       [ 1.44746750e+04,  1.64023812e+04],
       [ 1.36163586e+04,  1.15247356e+04],
       [ 2.20083085e+03,  1.96809151e+03],
       [ 1.82684300e+03,  4.47081644e+03],
       [ 3.94359540e+03,  5.82279872e+03],
       [ 2.07090203e+04,  1.57432127e+04],
       [ 5.61536900e+03,  4.77719116e+03],
       [ 8.96833000e+03,  1.06844610e+04],
       [ 1.08481343e+04,  1.37181236e+04],
       [ 2.95231656e+04,  3.74653072e+04],
       [ 1.73526803e+04,  2.51911399e+04],
       [ 4.91505985e+03,  4.81541525e+03],
       [ 9.63039700e+03,  1.18728649e+04],
       [ 1.00720551e+04,  1.16259919e+04],
       [ 1.23239360e+04,  1.14221260e+04],
       [ 1.86484217e+04,  2.73061461e+04],
       [ 6.28975490e+03,  9.82238823e+03],
       [ 1.36356379e+04,  1.58469434e+04],
       [ 4.35704365e+03,  5.63654757e+03],
       [ 1.29139924e+04,  1.20827142e+04],
       [ 1.27411675e+04,  1.55080610e+04],
       [ 2.46716633e+04,  6.24315772e+03],
       [ 8.12578450e+03,  1.23573015e+04],
       [ 6.75303800e+03,  4.63972071e+03]])

In [76]:
from sklearn.metrics import  r2_score

r2val = r2_score(y_test, y_pred)

print(f'Hasil Evaluasi R2   = {r2val}')

Hasil Evaluasi R2   = 0.7588793462249843

# Kesimpulan 
Variable bmi dan age menjadi variable independen yang memiliki korelasi yang kuat, dengan begitu variable tersebut memiliki nilai multicolleniarity yang tinggi. Dua variable tersebut menjadi variabel yang kurang tepat untuk model regresi.